### ISSUE TITLE
singularity

### ISSUE THREAD

**Issue by mgalland** [carpentries-incubator/docker-introduction#14]
Hello Docker enthusiasts, 

I am running a VIP workshop on Docker for our Amsterdam science park study group core members. The idea is to self-teach us Docker during an afternoon where we all sit down and go through your nice lesson material. I'll probably be able to spot a few issues and improvements.

Two questions:
- Do you agree to add an episode on Singularity and make a `singularity` branch & a pull request? 
- Do you have any wish list or already existing materials to guide this new episode section?

Thanks
Marc

**Comment by sstevens2** [comment]
Hi Marc!

We would be happy to have an episode on singularity.  I'm sure some lessons exist but I've not worked with singularity before so I am unfamiliar.  You could go ahead and make a branch with that new episode and submit it as a PR when you have a working version of the episode.

Let me know if you have further questions!  All feedback on the lesson welcome!
Best,
Sarah

**Comment by jcohen02** [comment]
Hi @mgalland and @sstevens2, we have some Singularity material that was added to an update of the original (pre-incubator) version of this Docker content and used in a [recent course](https://imperialcollegelondon.github.io/2020-07-13-Containers-Online/) (see episodes 11-16). Currently looking at the possibility of bringing this material into the incubator. I see that this issue was created a few months ago, have you had a chance to make any progress on preparing Singularity material yourself @mgalland?

**Comment by mgalland** [comment]
Hello @jcohen02. Not really. I ended up trying to get more familiar with Docker in the end. Singularity is still a bit away from my league I must say!
So please feel free to contribute, your material seems pretty awesome.

**Comment by jcohen02** [comment]
Thanks @mgalland, I didn't want to contribute anything without checking if you were already working on this and, if so, whether there was any scope to link combine or share material.

**Comment by jcohen02** [comment]
Just to update this, it was decided to include the singularity material as a separate lesson within the incubator - [singularity-introduction](https://github.com/carpentries-incubator/singularity-introduction). Since the Singularity material has now been imported into the new repository, I'm going to close this issue but feel free to reopen it, or open a new issue in the singularity-introduction repository if there are further questions around Singularity. Thanks.
