### ISSUE TITLE
DockerHub page

### ISSUE THREAD

**Issue by ChristinaLK** [carpentries-incubator/docker-introduction#16]
Want to add: 
- how to find images
- naming conventions + tags
- an exercise asking people to find an image to explore + to do so

Hopefully will have this done by next week.

**Comment by jsgro** [comment]
DockerHub page #16 says it's closed but I have the following to add... if this does not work here I'll open a new one.

It is casually said in the course (04-docker-hub/index.html, under bown box "What container is right for you?")  to "_Find a Docker container that’s relevant to you._"  I just want to point out that for a casual user this can be very frustrating for many reasons - and I have spent counless hours/days to make an image found on the hub to work! Reasons ranged from:

1. Entrypoint: error as the author assumed that the container would run on Linux and had a default to use X11. So it would fail... Only way was to use the by-pass entrypoint method.
2. Incomplete software within. This one was for sequence alignment (a complex meta aligner.) In the end I found that the image was missing some components, but it was not obvious. A change find of another image from someone else then worked.
3. Incomplete intructions or instructions that don't make sense -  some containers assume that you will use a web interface but there is no information on the web port that will work. Or require a secret password. 

Here is the point: there are lots (really a lot) of images on the hub that would need lots of TLC to make them work, or might never work at all. So, one should not keep high hopes that there is always a solution!

**Comment by ChristinaLK** [comment]
This is a good point! I think the DockerHub episode could provide more guidance on identifying containers that are likely to work easily and a short warning that it can sometimes be challenging to get more niche containers running.

**Comment by aturner-epcc** [comment]
I think we could usefully talk about image provenance here - showing how to identify official images in DockerHub (which would hopefully be more reliable) rather than those added by a random punter. This could then make the use of DockerHub less frustrating for a novice. Also briefly mention what the difference between an image and the "slim" version is.

**Comment by jcohen02** [comment]
Good point re _slim_ images @aturner-epcc. This was also something that came up when teaching the [Singularity lesson](https://github.com/carpentries-incubator/singularity-introduction) because we use a _slim_ version of the Docker Singularity image and there were some questions about the difference between the slim and regular versions of an image. This of course depends on the image and how the maintainer has decided to configure things but I think we could provide something very general in a callout.

I also agree with the point about image provenance and highlighting official images. I suppose the key point here is that anyone can upload an image to Docker Hub and people may upload images that are incomplete, untested, etc. The message is don't assume, just because it's on Docker Hub that this means it will work...

...of course many "unofficial" entities upload high-quality, tested, reliable images so perhaps this should just be a warning to use general caution when using unofficial images from Docker Hub, look for good quality documentation and descriptions of what the image does, how to use it etc?

**Comment by ChristinaLK** [comment]
> ...of course many "unofficial" entities upload high-quality, tested, reliable images so perhaps this should just be a warning to use general caution when using unofficial images from Docker Hub, look for good quality documentation and descriptions of what the image does, how to use it etc?

^^ I think this is exactly what I'm thinking - a short list of "good signs" and/or "red flags" when perusing images. Like: 

* is the image updated frequently
* is the image associated with a well established company, community, or other group
* does it have a Dockerfile
* does it have documentation

etc.
