### ISSUE TITLE
Run the Alpine Docker container, this isn't right

### ISSUE THREAD

**Issue by esloch** [carpentries-incubator/docker-introduction#22]
## Exploring and Running Containers

https://carpentries-incubator.github.io/docker-introduction/03-running-containers/index.html
```
Run the Alpine Docker container
Try downloading and running the alpine Docker container. You can do it in two steps, or one. What are they?

What happened when you ran the Alpine Docker container?

$ docker run alpine
Probably nothing! That’s because this particular container is designed for you to provide commands yourself. Try running this instead:
```

The result is:

> $ docker run alpine
> Unable to find image 'alpine:latest' locally
> latest: Pulling from library/alpine
> df20fa9351a1: Already exists 
> Digest: sha256:185518070891758909c9f839cf4ca393ee977ac378609f700f60a771a2dfe321
> Status: Downloaded newer image for alpine:latest

**Comment by sstevens2** [comment]
Thanks for reporting this issue @esloch .  This is a bit confusing because while it doesn't "run" anything in the container, it does download the image.  I'm thinking we should update the language to make that clearer, that it did download the image but no commands were run within the container.  Would you be interested in making a PR?
