### ISSUE TITLE
There aren't solutions or answers for exercises in chapter 7

### ISSUE THREAD

**Issue by aturner-epcc** [carpentries-incubator/docker-introduction#228]
Address issue raised in [peer review](https://github.com/carpentries-lab/reviews/issues/15)

**Comment by jcohen02** [comment]
I'm not sure about this one, @aturner-epcc - looking at the rendered version of the lesson, Chapter 7 is "Creating more complex container images" which is provided by `advanced-containers.md`.

From what I can see, all the exercises have solutions provided - they have the little "Show me the solution" drop down and solutions are provided.

The only thing I wondered is whether this point relates to the callouts with questions in them towards the top of the lesson - "Running containers" and "No such file or directory". These are added as challenge blocks but without a corresponding solution block - this in turn changes the icon to a little callout/chat symbol. In fact, the answers are then discussed below the box. I don't think it makes sense to put these answers in a "challenge/solution" block so that they have to be expanded, since I think they're intended as part of the content that the instructor works through so I think this is perhaps just more of a styling issue?
