### ISSUE TITLE
Using Docker with Jekyll example not working

### ISSUE THREAD

**Issue by vcasellesb** [carpentries-incubator/docker-introduction#245]
Hi! My name is Vicent Caselles, I'm a researcher working on biomedical image processing and I wanted to learn a little bit on Docker since I will be using it in my day-to-day in the short future.

First off, thanks for your great contents! I have walked through the whole tutorial, and I wanted to report some issues trying to generate the episode's website using the jekyll docker image (https://carpentries-incubator.github.io/docker-introduction/e02-jekyll-lesson-example.html). Namely, I am not able to find the folder that is mentioned in the tutorial, `docker-introduction-gh-pages`.  I've tried cloning this whole repo, and switching to branch `gh-pages` and then running the docker container using the command provided in the example:

```bash
docker container run --rm -it --mount type=bind,source=${PWD},target=/srv/jekyll -p 127.0.0.1:4000:4000 jekyll/jekyll:3 jekyll serve
```

However, when I load https://localhost:4000, it does not load anything. Is it possible I'm making some mistake?

Thanks. 
Vicent

**Comment by aturner-epcc** [comment]
Hi @vcasellesb . Apologies for the issue with this example. We have an issue open to remove this example as it is no longer valid with the switch to the new Carpentries workbench format (which no longer uses Jekyll to build the website). I will try and get this sorted out as soon as possible so others are not affected.

**Comment by jcohen02** [comment]
Hi @vcasellesb, thanks for highlighting this issue.

This is not working because fairly recently, our lesson, as part of a process being applied to all Carpentries lessons, was migrated to a new web template. The previous template was based on Jekyll and that's why we had this example in the lesson.

The new system, sandpaper isn't Jekyll based so the repository content has changed significantly and this Jekyll example will unfortunately no longer work.

We actually discussed this recently and added a note to #216 but it's clear that this needs removing as a matter of urgency so that other people don't get caught by this.

Apologies that you encountered this problem and thanks for highlighting it. We'll look into resolving this as quickly as possible.
