### ISSUE TITLE
CMD vs ENTRYPOINT

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/docker-introduction#41]
@chendaniely brought up the question of when you would use these two different options in a Dockerfile

[This link](https://phoenixnap.com/kb/docker-cmd-vs-entrypoint) has some clarification I found helpful.

Maybe we could add a section or call out in the "Creating More Complex Container Images" lesson to address this?

**Comment by hvwaldow** [comment]
I'd like to give that a shot. But to make things easier I think it would be good to change the recommended way to write CMD and ENTRYPOINT in *exec-form* instead of in *shell-form*. It is conceptually more clear (because *shell-form* actually just uses `/bin/sh -c` as executable). It is also the recommended way to do it according to docker docu ([CMD](https://docs.docker.com/engine/reference/builder/#cmd), [ENTRYPOINT](https://docs.docker.com/engine/reference/builder/#entrypoint)). You're ok with that?

**Comment by ChristinaLK** [comment]
I'd be okay with changing the format from shell-form to exec-form. 
shell-form is simpler (less cognitive overhead) but I think exec form is close enough that it shouldn't be too bad to add that extra concept.

**Comment by jsgro** [comment]
Entrypoint is a great feature... However, for the untrained docker user (like me) it can be extremely frustrating to not know how to "get into" the container and check things out, for example because the entrypoint command fails and then the container stops and we don't know why. 
Because of that I wrote a blog about this and how to by-pass the entrypoint: https://bcrf.biochem.wisc.edu/2019/10/31/docker-notes-bypass-entrypoint/

which contains 2 references to other blogs:

- How to properly override the ENTRYPOINT using docker run: 
https://oprea.rocks/blog/how-to-properly-override-the-entrypoint-using-docker-run/
(archived 11NOV 2019: bit.ly/2QFlGne)

- Docker RUN vs CMD vs ENTRYPOINT:
https://goinbigdata.com/docker-run-vs-cmd-vs-entrypoint/
(archived 25MAR 2019: bit.ly/35pg8Bj )

This may be the only way to get into a container and use a program even if the entrypoint command fails.

**Comment by ChristinaLK** [comment]
@jsgro your comment speaks more to the section of the lesson on *using* containers rather than the syntax for creating them with dockerfiles, so I'm going to create a new issue with your comment for additional discussion.

To recap: the suggestion in this issue is to use a different format for writing the container's default command in the sample Dockerfile. So instead of: 
```
CMD cat /etc/os-release && python3 --version
```
to use this notation instead: 
```
CMD ["cat", "/etc/os-release", "&&", "python3", "--version"]
```
@hvwaldow is this what you had in mind? 

I'm having mixed feelings again. I understand that the second option is recommended, but that (to me) isn't a good enough reason to use it because the first version is a LOT simpler and much closer to what a novice user already knows about (and, how the RUN options are structured in the file). Not to mention, less typing. :joy:

The more compelling reason (to me) is that if you want to use entrypoint later, the exec syntax is much more useful + powerful, so it might be helpful to see it in this context. I can see leaving the lesson the way it is, but including a callout that shows the alternative. 

@aturner-epcc @jcohen02 do you have thoughts on this?

**Comment by aturner-epcc** [comment]
So, I think I agree with your concerns around complexity here @ChristinaLK . There is already a lot of cognative load for beginners in this part of the lesson. I wonder if the useful compromise is to have a callout to the blog article that discusses the difference between CMD and ENTRYPOINT in the episode.

One thing I think we should do is explicitly note the differences between CMD and ENTRYPOINT (without mentioning those terms, as we have not covered Dockerfiles yet) at some point in the running containers section  as this has tripped up people when we have run the lessons. We could then call back to this point when we go on to discuss Dockerfiles and point to the blog. If we did want to add material explicitly covering this then I think it would need to go in an Extras episode.

**Comment by jcohen02** [comment]
Re _shell-form_ vs. _exec-form_, I'm happy to go either way but I do see @hvwaldow's point about _exec-form_ being the recommended approach. I certainly agree that shell form looks more straightforward when you're new to this and might be getting overloaded with lots of new information. At the same time, since we're trying to equip people who take the course with some general knowledge of Docker and the ability to write and understand `Dockerfile`s, if we don't cover _exec-form_ and that is the recommended approach and it's commonly used, will people then be confused when they look at a `Dockerfile` that uses this syntax? These are just my thoughts on this, as I say, I'm happy to go with either option.

I definitely think that we should note the difference between `CMD` and `ENTRYPOINT` and highlight the use of the `--entrypoint=` option. I actually thought that this was covered but I then recalled that when we ran the [Singularity lesson](https://github.com/carpentries-incubator/singularity-introduction) the other day, which uses Docker to run a Singularity container, one of the examples runs the container with `--entrypoint` to override the default entrypoint. This led to some useful discussion about what the `--entrypoint` switch does, the `CMD` and `ENTRYPOINT` options, etc. So it was actually in the Singularity lesson that we covered this 🙂. Even though I realise there's already a lot of material in the Docker lesson and a lot to take in, I think adding something that covers this would be good - maybe in a callout?

**Comment by ChristinaLK** [comment]
I think we could talk about there being two ways that `docker run` can invoke a default command, depending on the container, and maybe even show it as an optional exercise using the hello-world container. 

If I have time today or next week, I'll maybe work up a PR with my ideas and point you all at it to review. :)

**Comment by hvwaldow** [comment]
> ```
> CMD cat /etc/os-release && python3 --version
> ```
> 
> to use this notation instead:
> 
> ```
> CMD ["cat", "/etc/os-release", "&&", "python3", "--version"]
> ```
> 
> @hvwaldow is this what you had in mind?

Yes, @ChristinaLK, but your replacement code will not work (there is no shell to interpret "&&"). I believe this just shows that the shell-form might seem simpler at first but will produce confusion and hard-to find problems later.

Anyway, I created PR #63 to demonstrate what I imagine. It is not meant to short-circuit the discussion!

I think in favor of teaching *exec*-form is that it is more transparent. If you use *shell*-form you have to know and always keep in mind, that it actually means ["/bin/sh", "-c",  " ..."]. There are complications with shell-expansion, the question to which shell `/bin/sh` actually points in a given image, and really confusing behavior when combined with ENTRYPOINT. I believe the "official" recommendation is there for a good reason. 

Maybe a little comfort regarding the more complex syntax: People who are programming in Python will likely be used to that because `subprocess.run()` and colleagues have the same syntax.

I found a pretty good explanation  about the questions around CMD and ENTRYPOINT [here](https://aws.amazon.com/blogs/opensource/demystifying-entrypoint-cmd-docker)

**Comment by jsgro** [comment]
Just a quick "typo"-related note:
This entrypoint creates the command as `python3` which is useful as its specifies the number.
However, on page https://carpentries-incubator.github.io/docker-introduction/05b-advanced-containers/index.html
the command is:
 `docker run -v $PWD:/temp alice/alpine-python python /temp/sum.py` 
and therefore wont' work because it should be `python3` per the creation of the Image by the `Dockerfile`.

No "biggie" - and easy to fix... either on the page or let them fail and realize the error... (another example of needing to have specific info about the Image)

**Comment by hvwaldow** [comment]
> Just a quick "typo"-related note:
> This entrypoint creates the command as `python3` which is useful as its specifies the number.
> However, on page https://carpentries-incubator.github.io/docker-introduction/05b-advanced-containers/index.html
> the command is:
> `docker run -v $PWD:/temp alice/alpine-python python /temp/sum.py`
> and therefore wont' work because it should be `python3` per the creation of the Image by the `Dockerfile`.
> 
> No "biggie" - and easy to fix... either on the page or let them fail and realize the error... (another example of needing to have specific info about the Image)

https://github.com/carpentries-incubator/docker-introduction/pull/63/files#diff-d0cf2de18019fb7b377df785ccd66828f5afcba77a029c36aa442c54324f0a3dL95

**Comment by jcohen02** [comment]
Closing this now since the associated PR (#63) has been been merged and I think all the comments have been addressed. Thanks for the contribution @hvwaldow.
