### ISSUE TITLE
worth considering: how to avoid creating files outside the container as root on Linux

### ISSUE THREAD

**Issue by abotzki** [carpentries-incubator/docker-introduction#65]
Hi, 
I just wanted to point out something really useful when running e.g. bioinformatics tools with docker containers. 

This could fit here [Creating advanced containers](https://carpentries-incubator.github.io/docker-introduction/05b-advanced-containers/index.html) But on the other side, it will eventually make the duration of the episode a lot longer. 

It relates to the fact that if you run tools with docker containers which create output files outside the docker, so using the `-v` flag on Linux, you might create files with the owner root (it depends how the recipe is created though).

When using `-u="$(id -u):$(id -g)"` as additional flag running the container, you can avoid this surprise.

Maybe this is too advanced for your current course but I find it great that there is this run-time flag.

**Comment by ChristinaLK** [comment]
@abotzki great suggestion! I indeed use this flag myself when running certain containers locally. 

I wonder if we could reshape the "creating more complex containers" section to include a "more docker run options" section and include `-w` and the user flags there.

**Comment by jcohen02** [comment]
Thanks @abotzki, I agree that this is a great suggestion.

I see the possibilty of the `-u` switch perhaps making things a little confusing for new users but at the same time, I think it's realy good to highlight this. Perhaps along with other more advanced `docker run` options, as @ChristinaLK suggests, or just in a callout. 

We have encountered this issue when teaching the related [singularity-introduction](https://github.com/carpentries-incubator/singularity-introduction) lesson. We use the [Singularity Docker container](https://quay.io/repository/singularity/singularity) to enable participants to build Singularity images on their local system, even on platforms where Singularity is not directly supported. When we bind-mount a local directory into the Docker container as a place to write out the generated Singularity images, we encounter this issue with the ownership of the file on the user's filesystem after the container exits. I'll add a note about this to the singularity-introduction material too.

Interestingly, it looks like default behaviour is different on different platforms? If I try this on Linux, bind mount a directory and then create a file, when I exit the container, the file is owned by `root`, not my current user. Running on macOS (using Docker Desktop), it looks like the mapping is done by default because all the files in the bound directory from the host appear with `root` ownership inside the container and when I create a new file and then exit the container, it is owned by my user.

**Comment by abotzki** [comment]
Same here @jcohen02 - when preparing a Docker course recently, we have discovered the interesting behaviour of Docker containers. 

At the end of the road, the command line looks quite scary for beginners ;-)

```docker run --rm --name fastqc_albot -u="$(id -u):$(id -g)" -w="/data/" -v ~/workshop-janssen/data/:/data quay.io/biocontainers/fastqc:0.11.9--0 /bin/bash -c "fastqc WT*.fq.gz"```

the shell expansion part is not always necessary but depends on where you are in your folders on Linux.

Interesting that macOS could be more forgiving.

**Comment by hvwaldow** [comment]
Hi, I just wanted to chip in that I can confirm that issues around ownership / permissions of bind-mounted volumes are source of a great many confusions for learners who start playing around by themselves. I would like to put the option on the table that this could be dealt with not just under "another `docker run` option" but rather warrants a small section by itself, e.g. :

## Permission and ownership of bind-mounted volumes

1. (repeat) UNIX ownership concept: Defined by *uid* and *gid*, which is "attached" to each file as a number. Commands such as `ls` translate this number to a user-(group-)name. The mapping between the number and user-(group-) is held centrally on a system (in `/etc/passwd` and `/etc/group`). It is ok to have a file owned by uid(gid) for which no user(group) exists. `ls` then shows the number.
2. Commands run in a Docker container run per default under *uid 0*, which is associated with user *root* on any UNIX OS. That is the reason that files written to the host through a bind-mounted directory by a command given to `docker run` are owned by *root*, also on the host. Stress that uid and gid simply remain the same, regardless whether you are looking from the container or the host, just the interpretation as usernames might differ.
3. There are two issues resulting from that:
     3.1 It is very inconvenient if you don't own your analysis-output on the host. This can be remedied by using the `-u` option to `docker run`.
    3.2 Everybody who can connect to the docker daemon, that is **everybody who can use `docker run` on the host, has effectively `root access` on the host**. The same holds true for everybody who writes `docker-compose.yml` files that you use without having thoroughly checked them. This is a major security concern for the administrator of the host. It is the reason that admins of multi-user HPC clusters will often not run Docker but rather the alternative container system [*Singularity*](https://sylabs.io/). Alternatively you can [run the Docker daemon in *rootless mode*](https://docs.docker.com/engine/security/rootless/).

**Comment by ChristinaLK** [comment]
I'll note that I have never had any problems with file permissions/bind mounting running on a Mac. That said, I also am the only user + have full administrative access. 

@hvwaldow @jcohen02 @abotzki can you provide more specifics about the scenarios where this has happened, in terms of base operating system + the user's level of permissions within that system? i.e. if someone were to ask "how likely am I to encounter this problem?" what criteria would you tell them?

**Comment by jcohen02** [comment]
@ChristinaLK I certainly see this behaviour on Linux. e.g. on an Ubuntu 16.04 host with Docker 20.10.1 (although also tested with 19.03) where I am a signed in as a regular (i.e. non-privileged) user, but where the user has also been added to the `docker` group so they can run the `docker` command and start/stop/manage containers.

I'm assuming this is a fairly standard situation on Linux, although I guess the alternative is that the user doesn't want to add themselves to the `docker` group (assuming they're on their own system and have admin privileges to do this if they want to) and has to run docker commands prefixed with `sudo`. Nonetheless, I'm assuming that the behaviour would be the same in this case.

Just to confirm what I'm doing as my test, I'm using `docker run` and overriding the entrypoint with `--entrypoint=/bin/sh` (using a minimal container without `bash`) and also bind mounting a directory with `-v`. This is a directory which my user owns and where all the files within the directory are owned by me. When I look at the directory listing of the bind-mounted directory inside the container, I am the `root` user and I see the UID/GID of all the files being my UID/GID numbers on the host system (i.e. my user is not configured in the container so it doesn't know the user/group names of the file owner). If I then create a file in the bind-mounted directory, it's owned by `root:root` and when I exit the container, that's still the case on the host system.

On Mac I see different behaviour where when I enter the container (the same container with a bind mount set up, etc) the files in the bind-mounted directory in the container are all shown as being owned by `root` even though outside the container they're owned by my user on the system - docker is effectively mapping my user on the local system to root within the container. This way, when I create a file in the bind-mounted directory, it's shown as being owned by root in the container but when I exit the container, it's owned by my user on the host system. - I assume this is the same behaviour you see on your system @ChristinaLK?

Using the `-u` switch on Linux, as suggested by @abotzki, when I create a file within the container, it's given the ownership of my user on the host system so when I exit the container, I own any files created in the bind mounted directory. This is a little different to the behaviour on macOS but the end result is the same so I suppose this is a good solution on Linux.

Hope that all makes sense and I'm not confusing things with the above info! 🙂

**Comment by hvwaldow** [comment]
@ChristinaLK I am pretty sure that this (processes in a container runs as uid 0 per default and therefore produces files owned by root on the host through bind-mounts) is the normal and expected behavior on Linux systems. Docker for Desktop (or Docker for Mac) works very differently under the hood and apparently tries to match file ownership on the host to that of the host-user running `docker`. No idea what happens with Docker for Desktop on Windows. To answer your question:
Host Linux: 100%
Host Mac: 0%

**Comment by sstevens2** [comment]
Seems like there is agreement this should be added as a callout or section in the "creating more complex containers" lesson.  @ChristinaLK or @abotzki would you like to create a PR?

**Comment by abotzki** [comment]
@sstevens2 Yes, sounds fine with me. I am just wondering whether it fits seamlessly to the current content of the episode [Creating More Complex Container Images](https://carpentries-incubator.github.io/docker-introduction/05b-advanced-containers/index.html). As far as I see the Python script sum.py does not create any content when running.
So, I would add a somewhat more complex example where e.g. a tool (still to check what tools is most easy to use) would create some output files.
Does this make sense to you? Thanks.
