### ISSUE TITLE
alternative for "Containers used in generating this lesson"

### ISSUE THREAD

**Issue by jhidding** [carpentries-incubator/docker-introduction#76]
The current contents of "Containers used in generating this lesson" may not be ideal for every audience.

persona: Suppose a scientist has some small projects that they want to create a portfolio of. In that case it would be nice to be able to convert a README.md (or similar) to a website using `pandoc`.

I propose a chapter where we create a new project from scratch on Github. The project will only contain a readme file. Then we create a Github action that uses the `pandoc/core` docker container to convert the markdown to HTML and uploads the result to the `gh-pages` branch. This can be done in a minimalist fashion where a participant can understand each step in the process.

It should be noted that `pandoc` instances in package managers (why not just `apt install` it?) are often outdated.

#### questions
- How do I use docker from a Github Action?

#### objectives
- Awareness of possible use of Docker on cloud based source control platforms.
- Understand how Docker is called from a Github Action

#### keypoints
- Setting up a Github Action with Docker can automate every task.
- Docker gives ultimate flexibility in customizing and optimizing Github Actions (and similar concepts on competing platforms).

#### content
1. Create project with README
2. `git clone` and run `pandoc/core` image locally to show its function
3. Create Github Action
4. Watch magic happen

An example of the resulting project: https://github.com/jhidding/readme-pages

#### remarks
Pros: The advantage over the existing lesson is that the participants won't need to download a prepared project. This helps in empowering them to start using these methods in their own work. Using Github for this lesson ties in nicely with the Carpentries lessons on source control.
Cons: Using Github for this lesson widens the vendor lock-in on a monopolistic institution ;)

PR will be coming in the near future

**Comment by aturner-epcc** [comment]
@jhidding I think this is an interesting idea but am not convinced it is suitable for the core lesson. This introduces a whole slew of new concepts (git, github, github actions) which learners may not already have any experience of (this is an introductory lesson) and I think this is going too far. It could go into `_extras` as a replacement for this episode if you have confidence that the learners attending already have the experience required with git and github. I wonder if a better idea for this interesting material is a new, short (0.5 day?) lesson on using Docker in github actions that could be run in concert with this lesson?

**Comment by jhidding** [comment]
The same argument would go for both chapter 8 & 9 as they are now. Chapter 8 goes into using Docker with Bitbucket, while chapter 9 uses a very specific example with Jekyll. I agree that the use of Docker in Github Actions *could* take half a day if you discuss all the ins and outs, but that is by no means the goal of this. We (Netherlands eScience Center) have discussed this with the original authors of the lesson: the latter chapters are "extras" even as they are now.

In general, I think it makes little sense to talk about Docker without going into how it is used in some specific cases. Otherwise, why are we teaching this? The applications include:
- continuous integration
- deployment & dissemination
- computational workflows

Within those areas we should be looking for short and concise examples and make them work for the intended audience. In this case the intended audience is not the absolute beginner: yes we ask some prior experience with git and Github, but I don't think that is asking too much, considering the subject. I think this proposal fits these criteria.

**Comment by jcohen02** [comment]
@jhidding Thanks for providing this interesting suggestion for some new material in the introductory Docker lesson. Your proposed content helps to answer an important question about using Docker in a GitHub Actions environment, however, I'm inclined to agree with @aturner-epcc that this would fit better as an independent set of material, or perhaps as an exercise within a CI lesson focusing on GitHub Actions?

While the Docker introductory course could be classed as more of an intermediate level carpentries course - we expect some level of base knowledge, such as being comfortable with working at the command line - I think we're keen to keep the number of areas of prerequisite knowledge as small as possible. While it might be reasonable to assume that attendees probably know what Git is and are likely to be experienced using it, we don't know this for sure and I would think that for anyone not familiar with GitHub Actions, this might take a little time to explain and would move us somewhat away from the core topic.

When we've run the course previously, the practical aspects of this episode can be covered very quickly - it should just be as simple as downloading and unzipping the file containing the repository contents, changing into the directory and then running the docker command provided. This then gives us quite a bit of time to explain what is happening, what all the command line flags mean and how the example works. Nonetheless, I can see that the example is still, perhaps a little contrived so it may be that it we can change/improve the story or use case.

**Comment by jhidding** [comment]
A bit more context: we are teaching this workshop on Tuesday (23rd). As a matter of preparation I'm working on this example. We will be doing this in the form of a live demo (optional code along), maybe even more as a replacement of chapter 8 (using Bitbucket) than 9. We'd like to feedback our experience on this lesson to the community. I'm fine setting this off in `_extras`, but then so should existing chapters 8-10 go there.

**Comment by aturner-epcc** [comment]
@jhidding I totally agree that the lesson overall would be strengthened by the addition of concrete use cases and I also agree that this episode is one of the places we should look to do that by making the example more relevant to a research audience. My reservations are not that something should not be added but rather that the specific example you are proposing here introduces too many new concepts for the level of the lesson. I am happy to be convinced otherwise and would value the thoughts of @sstevens2 and @ChristinaLK here.

FWIW, my experience of teaching this episode is that it does serve a useful purpose even with Jekyll. Typically, we do not explain anything about Jekyll other than: "it is the software used to build websites by Github pages and it is a pain to install" and that we are using it as an example of how Docker address the issue of complex software installs and dependency issues so there is no complexity of explanation.

As for episode 8 (bitbucket), I must admit that I have always removed that episode when teaching this lesson as it does seem to not quite fit. We are currently discussing how to address this by either adding a containers in the cloud episode in extras or potentially developing a short standalone additional lesson to cover this area.

Thanks again for raising this as I do think the lesson needs improvement here.

**Comment by sstevens2** [comment]
@jhidding Thanks for your suggestion and for bringing up the issues with episodes 8 and 9.  

Regarding episodes 8 and 9, we discussed these episodes at our recent maintainer meeting earlier in the week.
- For the "Creating containers in the cloud" episode we decided to move it to extras and it will be redesigned by @dme26 and @jcohen02.  
- For "Containers used in generating this lesson", we also thought that other examples should be added to show how this is being used as there was concern that Jekyll wasn't a relevant example for some audiences. @aturner-epcc and @jcohen02 provided helpful feedback from their experience teaching the lesson that this a good "ah-ha" moment for learners to see how it can solve an issue with a complicated install like Jekyll.  We decided to keep it but look at adding other options and restructuring as a "choose your own adventure" lesson. Looking at this episode, I don't think the language is clear on _why_ we are generating the lesson locally (as an example of how it can avoid installing difficult software).  I think we should add some text to this episode to clarify that. I think that motivational text will be helpful as we move this episode to have more several examples.

I think we should add this Github Actions lesson in as an extra.  I am also concerned that Github Actions might be a bit too much cognitive load for learners.  @jhidding  I'll try to review your PR as soon as possible and I would love to hear your feedback about how it goes when you teach it.  Since we are restructuring the "Containers used in generating this lesson" episode, we can later consider bringing it into this lesson as part of that restructure.

**Suggested action items**
1. Review GitHub Actions PR 
2. Create issue about adding additional motivation language to the "Containers used in generating this lesson" and maybe retitling 
3. Create issue about moving the "Creating containers in the cloud" episode to extras and assign to @dme26 and @jcohen02 
3. Start a discussion to discuss other examples that we might want to include as possibilities for the "Containers used in generating this lesson" episode.
