### ISSUE TITLE
Can we install Docker via Homebrew or MacPorts for older OSX?

### ISSUE THREAD

**Issue by dmwelch** [carpentries-incubator/docker-introduction#88]
In the setup, it doesn't mention either Homebrew or MacPorts as an installation option.  Have either of these been tested on an older Mac, @jcohen02 ?

**Comment by jcohen02** [comment]
Thanks for highlighting this @dmwelch. I haven't personally tested installation of Docker via MacPorts or Homebrew, I've always used the main [Docker Desktop installer](https://docs.docker.com/docker-for-mac/install/) on MacOS.

I think we'd strongly recommend this as the most straightforward way to receive the latest Docker release and get regular updates, especially given that the software seems to be updated fairly regularly.

However, I guess we could add a box highlighting that if a user experiences issues installing via the main Docker Desktop installer (e.g. their release of MacOS is too old to support it), then there is also the possibility to install via the widely used MacOS package managers MacPorts and Homebrew. I think we should add a caveat stating that to ensure that you receive a version of Docker that includes the latest security fixes, we strongly recommend updating your system to a recent macOS release so that you can install the latest version of Docker.

A quick look at the MacPorts and Homebrew configurations for Docker seems to suggest that Homebrew just downloads and runs a Docker installer anyway? For MacPorts, it looks like it's installing a release from GitHub so I assume this will just install Docker Engine providing Docker on the command line. Do you have any experience of using these versions @dmwelch?

**Comment by dmwelch** [comment]
I don't, but I was curious about the install notes for older Macs specifically.  I don't have an older one to test on so I was trying to figure out if those options might work for them.  🤷‍♂️

**Comment by chendaniely** [comment]
Can you define "old"? I have a MacBook Pro 13-inch retina Late 2013 model I can give this all a test in.

**Comment by chendaniely** [comment]
confirming that you can install docker using homebrew using `brew install --cask docker` (note homebrew has changed away from `brew cask install`). you have to run the docker gui manually once to do all the initial setup (since it's a GUI application).

Once do that, you have the `docker` function in the terminal and can `docker pull` and `docker run` an image.

I used the `hello-world` example docker image: `docker pull hello-world`, and then `docker run hello-world` returns text from the image.


I haven't tested this using macports.

So this issue can probably be closed.

**Comment by dme26** [comment]
Much appreciated @chendaniely and I'll close this after checking that it's mentioned that the Homebrew route has been tested.

**Comment by jcohen02** [comment]
Sorry to comment further on this after it's been closed but I was just taking a look at this again re supported versions of macOS for Docker. I think the point about installing on older Macs presumably relates to the operating system version (i.e. systems that may still be running old OS X releases such as El Capitan (10.11), Sierra (10.12), etc.)

I note that that both the homebrew cask and Docker's own Docker Desktop install for Mac require a minimum macOS version of Mojave (10.14). I think it's great to include the hombrew instructions there but I'm going to add a mention of the minimum required macOS release being 10.14 to ensure things are clear. There's then the instructions about using the old Docker Toolbox if you've got an older version of macOS which I think it's useful to retain (assuming this is still available for download...I'll double check).

**Comment by kupietools** [comment]
NB installing Docker with MacPorts on Mojave doesn't leave you with a working Docker install, something else is required but nowhere is it made clear exactly what. `docker pull hello-world` returns `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`. I'd just use Docker Desktop, but they've deleted the download links for the last version that ran on Mojave.

**Comment by jcohen02** [comment]
Thanks for raising this @kupietools. If you've installed the "docker" port from MacPorts [https://ports.macports.org/port/docker/details/](https://ports.macports.org/port/docker/details/), it looks like this contains only the docker command line tools, not the actual docker daemon itself, hence the message that the daemon is not running.

The suggestion in the info for the port is to install the "[colima](https://ports.macports.org/port/lima/details/)" port but that unfortunately won't help you since it seems to only work with macOS 11+.

You could take a look at the main [lima repository](https://github.com/lima-vm/lima) and see if there's any information there about running on older versions of macOS. I couldn't find any details there but I'm sure I recall successfully running lima on macOS 10.15 so there may possible be support for 10.14. Sorry I can't offer more help on this one.
