### ISSUE TITLE
Planning Upcoming Sprint

### ISSUE THREAD

**Issue by sstevens2** [carpentries-incubator/docker-introduction#94]
Hi all!

At the April Maintainers Meeting, the @carpentries-incubator/docker-introduction-maintainers decided to hold a lesson sprint.  What do folks think about **June 2nd-June 3rd** (UTC)? I made a draft schedule below with the regions of the maintainers.  It isn't a full day but it gets more tricky after the hours I included since there is a larger distance between NZ and UK.  It is somewhat US centric for the same reason and as was really hoping to be there at the beginning.

Some initial thoughts:
- Include a scheduled time to discuss the singularity lesson in the sprint as well
- Co-work to close issues and get the lesson to a slightly more stable form for release.

13 UTC - 16 UTC - Start the Sprint - US and UK Time regions
16 UTC - 17 UTC - Break
17 UTC - 20 UTC - Co-work - US  (optional UK)
20 UTC - 21 UTC - Break
21 UTC - 24 UTC - Co-work - NZ (optional US)
 0 UTC -    1 UTC - Break
  1 UTC -   4 UTC - Co-work - NZ (optional US)

**Comment by jcohen02** [comment]
Thanks for this @sstevens2, both the suggested date(s) and the schedule would work for me.

Might it be worth trying to add a 1-hour sesssion to the start where we can, potentially, all be present to discuss plans for the sprint? I can see this is very difficult with timing and this would end up being separated from the main spring schedule - I guess it would have to be something like 19-20 or 20-21 UTC (1st June). This is not ideal for UK and probably not for NZ either but if there is general consensus that this would be useful and everyone was OK with the timing, I'd be willing to attend a sprint intro session in one of these slots. Otherwise happy to stick with your suggested schedule.

**Comment by sstevens2** [comment]
Good idea!  I also think it would be nice to have a pre-sprint meeting June 1st.  What do other's think? @aturner-epcc @ChristinaLK @dme26

**Comment by aturner-epcc** [comment]
I think a pre-sprint meeting would be useful too but I will struggle to make 20-21 UTC. I know this is the more convenient for NZ so please do not feel constrained by me - I can always catch up with Jeremy on Wednesday morning UK time.

1-3 June are fine for me.

**Comment by ChristinaLK** [comment]
June 1st I have office hours during the suggested meeting time(s) and may be coming back from a vacation. 
I also need to think about vacation time that I'll need to take to work on this. 

Basically - keep planning, and I'll make it work but I definitely will be doing other work at the same time, at least a little bit.

**Comment by dme26** [comment]
Hi @sstevens2 and all. Thanks for initiating this planning.
- I've put the sprint blocks into my diary: fits well for me.
- Pre-meeting sounds like a good idea.
- Suggested pre-meeting times work for me, but I've not put anything into my diary yet.

**Comment by sstevens2** [comment]
Sent out email invite for the pre-meeting and for the docker sprint.  Started [sprint document](https://codimd.carpentries.org/NkXLufmISEKHemNtR_8Kuw?edit).  Would love to get feedback on that doc from the @carpentries-incubator/docker-introduction-maintainers.  I'd like to invite other folks in the docker and maintainers slack channels to join if they would like next week.

**Comment by jcohen02** [comment]
Thanks for preparing the sprint document @sstevens2. 

Not sure on the best way to provide feedback or suggested updates on a codimd document, although I've only got a few comments to make so adding them here (_I note that codimd doesn't seem to have the same [comment functionality](https://hackmd.io/s/how-to-use-comments) as [HackMD](https://hackmd.io/) even though the interface otherwise looks very similar_).

 - Goals: I definitely agree we should be moving towards a stable release, however, I wonder how far it's realistic to get in a 1-day sprint? Is the plan that we should be looking to have a version ready for Zenodo at the end of the sprint? Certainly reasonable to have this as an ultimate aim.
 - Something we could add is to look at clarifying optional episodes and possibly providing recommended training paths/schedules - i.e. groups of core and optional episodes that work well for particular use cases? This will contribute to the second goal.
 - Is it worth adding a sprint tag and then using the 1 hour pre-sprint meeting to do an issue triage and tag things we think it's realistic to address during the sprint?

Anyway, this looks like a great template to base the sprint on. Also very happy to invite others to get involved if they'd like to.

**Comment by sstevens2** [comment]
Thanks @jcohen02!  

> * Goals: I definitely agree we should be moving towards a stable release, however, I wonder how far it's realistic to get in a 1-day sprint? Is the plan that we should be looking to have a version ready for Zenodo at the end of the sprint? Certainly reasonable to have this as an ultimate aim.
I think we should go ahead and set the goal for a stable release that we can publish with zenodo.  If we don't get to it by the end of the sprint, we can re-evaluate and make a plan for what is left.

> * Something we could add is to look at clarifying optional episodes and possibly providing recommended training paths/schedules - i.e. groups of core and optional episodes that work well for particular use cases? This will contribute to the second goal.
- I think this is a great topic for discussion!  Would you mind adding this as a discussion topic for one of the sessions?

> * Is it worth adding a sprint tag and then using the 1 hour pre-sprint meeting to do an issue triage and tag things we think it's realistic to address during the sprint?
> 
- Think we should use the [Beta 2.0 Project](https://github.com/carpentries-incubator/docker-introduction/projects/1) we setup (linked on line 34 of the sprint document as well) to coordinate issues for the sprint.  I agree we should review these at the pre-sprint meeting.

**Comment by sstevens2** [comment]
Sprint in action, closing this issue
